version: '3.8'

services:
  nginx:
    image: nginx:1.19.1-alpine
    command: EXPOSED_PORT=${EXPOSED_PORT:-} nginx -g daemon off
    networks:
      - traefik-public
      - php
    volumes:
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
      - './src:/var/www'
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.website-rieke.rule=Host(`riekehelmers.com`)'
        - 'traefik.http.services.website-rieke.loadbalancer.server.port=80'
  php-fpm:
    image: jonaskuske/php-fpm-imagemagick
    networks:
      - php
    volumes:
      - './src:/var/www'

networks:
  php:
    driver: overlay
  traefik-public:
    external: true
