version: '3.8'

services:
  nginx:
    image: nginx:1.19.1-alpine
    env_file: .env
    environment:
      - EXPOSED_PORT
    networks:
      - php
    volumes:
      - './nginx.conf:/etc/nginx/templates/default.conf.template'
      - './src:/var/www'
  php-fpm:
    build:
      context: .
      args:
        DEVELOPMENT: 'true'
    user: '${UID}:${GID}'
    networks:
      - php
    volumes:
      - './src:/var/www'

networks:
  php:
