Title: Project

tabs:
  content:
    label: Inhalt
    icon: text
    fields:
      projectThumbnail:
        type: files
        multiple: false
        label: Thumbnail
        uploads:
          maxwidth: 3000
      gallery:
        type: files
        multiple: true
        label: Galerie
        uploads:
          maxwidth: 3000
      video:
        type: url
        multiple: false
        label: Video-Link
      text:
        type: blocks
        label: Text
      date:
        type: text
        label: Datum
  seotab: seo
