Title: Project

fields:
  projectThumbnail:
    type: files
    multiple: false
    label: Thumbnail
  gallery:
    type: files
    multiple: true
    label: Galerie
  video:
    type: url
    multiple: false
    label: Video-Link
  text:
    type: blocks
    label: Text
  date:
    type: text
    label: Datum
