# More about the site blueprint: https://getkirby.com/docs/reference/panel/blueprints/site

title: Site

tabs:
  content:
    label: Übersicht
    icon: grid
    columns:
      - width: 2/3
        sections:
          projects:
            extends: sections/projects
            headline: Veröffentlicht
            status: published
            search: true
      - width: 1/3
        sections:
          pages:
            type: pages
            label: Seiten
            create: default
          fields:
            fields:
              logo:
                label: Logo (Lightmode)
                type: files
                multiple: false
              logoDark:
                label: Logo (Darkmode)
                type: files
                multiple: false
              socialLinks:
                label: Menü-Links
                type: structure
                fields:
                  name:
                    type: text
                    label: Name
                  url: true
  seotab: seo
